Remove sfml (#149)
* include glengine into sfml

* wip extract glengine from imgui. might be broken

* okay opengl version compiles again

* imgui not required by glengine

maybe mistake i donno

* not using the grid.cpp control anymore

I've been using imgui to draw the grid lines.

* remove sf::Texture

Well it compiles but it isn't working lol alot of bugs to fix.

* add stack trace to my gl error code

this is more useful than just source location.

* fix the new tile button

this was done because we have a texture in there. and we need to draw the clear button. Might be changing things later so we aren't generating 3 textures every frame. We just need to store these buttons in gui.hpp.

* fix opengl context closing early.

more work on create_color_button too

* save configuration on exit

* move key_to_string to the header

* load the window size from the config

* try having texture defined in gui contructor meant glew needed to be init earlier.

buttons not showing for some reason.

* texture page grid was broken for mim.

* remove RenderTarget code from mim_sprite

* wip replace sf::rendertexture

* wip replace sf::rendertexture

fix unique value wasn't unbinding the framebuffer.

* add batchrenderer

not even using yet but I'm trying to lol
SFML-imgui was wanting to have everything in a default state before it'd work.
I moved the res folder too since sfml will need access to the shaders.

* changed scope guard in glengine

also moved OrthographicCamera back into glengine removed imgui from it

* remove scope_guard to use glengine::ScopeGuard.

* fix map rendering

get_color_attachment -> bind_color_attachment
because this binds the color attachment as a texture to slot 0.
+ color_attachment_id so we can just get the id.
+ sf::ContextSettings to test different versions of opengl.
+ m_max_textures  using a private value instead of a static one.
BatchRenderer backup now restores the active texture and the shader.

* selections_force_rendering_of_map

* blending is working

u_Color -> u_Tint
+BlendModeSettings moving functions from Window.
fix blending modes using gpt for help.
+Vertex.cpp moving function bodies to the cpp file.
Add missing headers
move set_uniform to Shader.cpp reorder some functions.
+enable_blending

* if (!m_disable_blends)

* fix saving image with save_image_pbo

fix set_uniforms
moved some code from another function into generate_texture so should be able to use the code to draw.
Some of the async code doesn't need to be there.
I'm wondering if the framebuffer needs to survive I'm not sure we might run into issues if the frame buffer goes out of scope. or if i just like write over the old textures while it's running. I'll see what happens. The original code did keep the framebuffer in the future so i might need to do that.

* glengine::FrameBuffer is no longer by reference

so we can either clone or move it into the copy function. Because it needs to live the duration or the copy atleast I think so.

* clone function in frame buffer

* wip on fixing saving batches.

* future consumer can now take in more than one range.

using += to add ranges to the queue.
also changed to move only to make sure I'm not copying any of these.

* change to += for future consumer

* saving selected fields in the map list on batch screen

* saving pupu and swizzles are working

* Update Shader.hpp

add nodiscard

* sf::Vector to glm::vec

commented out square I think it wasn't working anyway.

cleaned up get_triangle_strip math added argument for texture_size and renamed arguments to make sense.

* Update map_operation.hpp

add doxygen comment

* I don't think we need square anymore

* Update CMakeLists.txt

remove square.cpp

* Vector2f to vec2

comment out RenderTexture related code.

* remove/commented out more of SFML

TODO fix png image loading.

* sf::Image -> glengine::Image

this only loads pngs. So we'd need to add support for other formats maybe one day. heh.

* FutureOfFutureConsumer vector based

* move future consume into header

* remove reset_render_texture and init_render_texture

* okay so the textures are loading but it's not perfect.

I wanted delayed texture loading to work.

* attempt to improve consumers

using std::exhange seems better when possible. filter out invalid futures before passing them on.

* Update map_sprite.cpp

local_draw didn't finish the draw before resetting the blend.

* make sure textures get loaded.

fallback_textures function now will check to see if textures are loaded if not it disables loading png textures and reloads.
i had to make some values mutable and some functions const because saving the displayed image as png would run functions to make sure the textures are loaded first.

* move path cache into selections and store in toml

* encode vector of bool as strings

* Update Selections.cpp

I had the configkeys in a different order than the varibles. oops.

* wip on async path loading.

* fix crashing async code wip

new async code was crashing app so restructured app to help prevent crashing.

s I said though it does feel noticeable that the ui is more responsive. Though I did get it to crash by clicking next over and over.
[2025-06-23 19:06:03.635] [error] Unexpected exception in wait_for: bad allocation
[2025-06-23 19:06:03.639] [warning] Skipping future: no valid state (possibly moved-from or default-constructed), D:\dev\Field-Map-Editor\src\sfml\RangeConsumer.hpp:404

I need to do more isolation heh sadly async is a landmine of race conditions. if you don't like move or copy everything you're gonna use it'll crash randomly.
Sebanisu — 11:29 PM
I moved a bunch of code around and it seems more stable now. Though I need to do code clean up and fix TODOs that i skipped over trying to get it to compile heh.
i just spammed the heck out of the next button and it isn't crashing so goal achieved i guess. heh. Before it would definitely crash.
I kinda wish the framebuffer wasn't cleared out when i switched fields. but instead waited till the textures were loaded before being cleared out. I could maybe forward it to the new instance.

* improve framebuffer.clone

it wasn't working 100% of the time. still can only clone RGB textures. I worry about the redinteger right now.

I wanted to pass the framebuffer to prevent the screen going black when you toggle between fields. After a few seconds the textures are loaded and the framebuffer is recreated.

* Update FrameBufferBackup.cpp

fix types

* force_rendering_of_map to force loading of textures when enabled.

* Create checkerboard.shader

wip

* fix not using target

* color to vec4

* stacktrace

* add size overload

* Update checkerboard.shader

fix shader

* replace checkerboard pattern with shader and framebuffer.

* I tried to work on TODOs. to fix things i had left broken.

Also add dims check before creating checkerboard framebuffer.

* Update gui.cpp

remove the old checkerboard code.

* remove commented

gpt says i should use this cast

* todo, float, time

check for invalid floats lol
remove todos
switch from sf::Time

* sf::IntRect -> glm::ivec4

the member names are a little different like width is z and height is w. heh

* wip sfml removal mostly done

* add close button to windows

fix shortcuts
add     m_field_file_window.refresh(m_field); because sometimes it'd be null

* remove more sfml and remove events

make_visitor moved into collapsing tile info where it is used.
import was saving every frame. so i commented out saving.
selections_display_import_image_window
DisplayImportImageWindow
so we weren't actually doing a seperate toggle for drawing the window and drawing the texture.

Updated readme.

* move sfml folder to opengl

* rename sfml folder to main

* opengl_version -> experimental

* Update CMakeLists.txt

 ${PROJECT_NAME}_OPENGL to  ${PROJECT_NAME}_EXPERIMENTAL

* add extension

* custom filename for experimental

* ${PROJECT_NAME}_SFML to  ${PROJECT_NAME}_MAIN

* remove more of the SFML rename imgui.ini and move to res

* add icon

* extract draw_window from gui class

I have made a control window file but it isn't done yet.

* fix update tile indices

* Fix bug causing color button not to display by storing tile_button_options by value instead of reference.

Previously, m_options was stored as a reference (const tile_button_options&), which became dangling when create_color_button was constructed with a temporary.

This led to invalid values (e.g., size, colors), causing ImGui::ImageButton to silently render incorrectly or not at all.

Now m_options is stored by value to ensure a valid copy with proper lifetime.

Also explicitly initialized m_transparent_texture using the Transparent color.

* remove control_panel_window.cpp

the window is too coupled with gui.cpp so we aren't doing this right now.

* add spdlog messages and fix comment

* add scale to framebuffer

This is a helper value. So that things that are drawing to the frame buffer know the size to draw or for overlaying items like grid lines and such. framebuffer itself doesn't care about the scale.

* use move only functions to pass in getter for paths

we're doing this to make sure the paths are fetched in the async thread instead of in the main thread.

* disable delaying timer for consuming futures.

use helper functions for generating paths.

* add spaceship <=> to setting backup

also change to signed int.

* add ImGuizmo

* these asserts were broken i changed from shared ptr to reference

* BeginFrame neeed to be after NewFrame.

* Add Guizmo

it's a wip but it is interactive and working lol.

* gizmos tweaks

add ability to remove selected tiles.
escape removes all selected tiles
adjust scale of gizmos

* add TheCherno

* fix guizmo to work with scroll bars

* update down_pixel when click happens.

remove on_click_not_imgui

* update position of tiles fixed with guizmo

* move definitions of functions into maphistory.cpp

wasn't planned i was looking in the wrong maphistory lol

* added begin_working_copy end_working_copy

m_in_multi_frame_operation
begin_multi_frame_working
end_multi_frame_working
m_translation_in_progress

goal was to prevent the flood of info going into the history.

* update the description after the move with the delta

* fix crash when drag on swizzle

also removed limit on not letting us move tiles to where tiles exist already.
also texture page is no longer a parameter we can calculate it.

* fix when scrolling

* add Edge scrolling when dragging a gizmo

also add const in places.
ImVec2 operator-

* added ()

appveyor using old msvc which requires () for lambdas.

* found more lambda missing ()

old version of msvc requries the ()

* disable import window

there is alot to do and i don't want to hold up merging to fix it right now.

* alter the bpp to stay valid when changing x position.

fixes https://github.com/Sebanisu/Field-Map-Editor/issues/81

* remove commented code that restricted placement of tiles

* change collapsing_tile_info to take two values

one for getting the image. the other for the new values.

* show what values have changed in collapsing_tile_info

we also added a new color

* color menu now has 2 columns

* add filter to field picker

* Update LayerItem.hpp

#include <utility>
#include <memory>
headers missing
gcc called it out.

* Update MenuItem.hpp

#include <memory>
#include <type_traits>
#include <utility>
gcc strick on missing headers

* Update filter.hpp

-Werror=ignored-qualifiers const does nothing.

* Update MapHistory.hpp

-Wtemplate-body

these functions were missing a parameter but only gcc is evaluating them. msvc skipped them because they aren't called.

* Update VertexArray.hpp

[-Wtemplate-body]
backup isn't defined before it's used in a template

* Update IndexBufferDynamic.hpp

[-Wtemplate-body]

* Update VertexBufferDynamic.hpp

 conversion to 'GLuint' {aka 'unsigned int'} from 'GLint' {aka 'int'} may change the sign of the result [-Werror=sign-conversion]

* Update BatchRenderer.cpp

[-Werror=reorder]

* Update BatchRenderer.cpp

[-Werror=reorder]

* Update filter.hpp

fix narrowing conversion.

* comment out display import image window

will never be NULL [-Werror=address]

* Update gui.cpp

[-Werror=switch]
I'm using an enum in a switch case but I don't care about the other values. but gcc hates me. so i put a default case there.

* Update gui.cpp

 [-Werror=sign-conversion]

* Update gui.hpp

[-Werror=ignored-qualifiers]
also not even using that function anymore

* Update generic_combo.hpp

[-Werror=shadow]

* Update normalized_source_tile.hpp

 error: no type named 'impl_type' in 'std::remove_cvref_t<open_viii::graphics::background::normalized_source_tile>' {aka 'struct open_viii::graphics::background::normalized_source_tile'}

* Update filter.hpp

 [-Werror=narrowing]

* Update README.md

wip documentation update for compiling to arch linux

* Update batch.cpp

[-Werror=sign-conversion]

* Update batch.cpp

oops [-Werror=sign-conversion] fix wasn't right heh.

* Update batch.cpp

[-Werror=sign-conversion]

* Update batch.cpp

[-Werror=unused-but-set-variable]

* Update batch.cpp

[-Werror=switch]

* Update batch.cpp

added braces

* Update draw_window.cpp

[-Werror=range-loop-construct]

* Update Selections.cpp

[-Werror=narrowing]

* Update draw_window.cpp

[-Werror=useless-cast]

* Update draw_window.cpp

[-Werror=conversion]
[-Werror=useless-cast]

* Update draw_window.cpp

[-Werror=conversion]
[-Werror=old-style-cast]
[-Werror=useless-cast]

* Update collapsing_tile_info.cpp

[-Werror=conversion]

* Update Selections.hpp

[-Werror=sign-conversion]

* Update import.cpp

[-Werror=conversion]

* Update create_tile_button.cpp

[-Werror=conversion]

* Update import.cpp

[-Werror=sign-conversion]

* Update Selections.hpp

[-Werror=sign-conversion]

* Update format_imgui_text.hpp

[-Werror=sign-conversion]

* Update import.cpp

unused values in imports [-Werror=unused-but-set-variable]

* [-Werror=unused-variable]

* Update map_operation.cpp

[-Werror=unused-but-set-variable]

* Update map_operation.cpp

[-Werror=range-loop-construct]

* Update map_sprite.cpp

[-Werror=unused-but-set-variable]

* Update map_operation.hpp

[-Werror=sign-conversion]

* Update map_operation.hpp

expression cannot be used as a function [-Wtemplate-body]

* Update custom_paths_window.cpp

[-Werror=stringop-truncation]
[-Werror=switch]

* Update custom_paths_window.cpp

 [-Werror=range-loop-construct]

* Update custom_paths_window.cpp

[-Werror=sign-conversion]

* Update future_operations.cpp

[-Werror=sign-conversion]

* Update save_image_pbo.cpp

[-Werror=useless-cast]

* Update map_sprite.cpp

[-Werror=reorder]

* Update map_sprite.cpp

[-Werror=unused-but-set-variable]

* Update map_sprite.cpp

standard attributes in middle of decl-specifiers

* Update map_sprite.cpp

[-Werror=sign-conversion]

* Update custom_paths_window.cpp

[-Werror=implicit-fallthrough=]

* Update map_sprite.cpp

[-Werror=sign-conversion]

* Update map_sprite.cpp

[-Werror=useless-cast]

* Update map_sprite.cpp

[-Werror=useless-cast]

* Update map_sprite.cpp

[-Werror=sign-conversion]

* Update map_sprite.cpp

 [-Werror=sign-conversion]

* Update custom_paths_window.cpp

[-Werror=implicit-fallthrough=]

* Update map_sprite.cpp

[-Werror=reorder]

* Update map_sprite.cpp

[-Werror=sign-compare]

* Update map_sprite.cpp

[-Werror=sign-conversion]

* Update custom_paths_window.cpp

[-Werror=implicit-fallthrough=]

* Update map_sprite.cpp

[-Werror=sign-conversion]

* Update map_sprite.cpp

[-Werror=useless-cast]

* Update map_sprite.cpp

 [-Werror=sign-conversion]

* Update map_sprite.cpp

[-Werror=sign-conversion]

* Update map_sprite.cpp

[-Werror=sign-conversion]

* Update map_sprite.cpp

[-Werror=sign-conversion]

* Update map_sprite.cpp

[-Werror=useless-cast]

* linking errors with stacktrace gcc

* Update README.md

add git and such to instructions

* Update README.md

image of running on arch

* m_map_group.field.expired

There was code running even when field is null. causing errors in the terminal.

* Update README.md

fix last bit of linux stuff

* Update batch.cpp

disabled limiters so the operations will go as fast as possible.
also i tried to stop the loading of a map_sprite when we don't have a valid coo and field combo.

* Update map_operation.cpp

Warning wasn't clear. So I added a specific one about how raw_map can be empty because it didn't exist.

* Update map_sprite.cpp

check to make sure selections isn't expired too.

* add a ForceReloadingOfTextures

before the ForceRenderingOfMap did this function but I wanted to allowe just ForceRenderingOfMap by it's self. So we didn't need to reload the textures. heh. This bassically locks the debug mode because loading textures is so hard on it.

* Update BlendModeSettings.cpp

fixes https://github.com/Sebanisu/Field-Map-Editor/issues/154

* Add Filtertags for swizzle_one_image

* Update filter.hpp

filter_swizzle_as_one_image_map filter_swizzle_as_one_image

* wip input swizzle as one image

also renamed some funtions for clarity. I added functions and changed funtions for supporting loading from swizzled and one image textures.

* don't reload textures when loading a .map file

* incorrect name for varible name

* copy and paste errors.

* upscale to swizzle

* renamed things from Upscale to Swizzle

though i didn't go all the way lol. there are alot of instances.